project:
  type: website
  output-dir: docs

website:
  title: "Davi Moreira"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
      - href: books.qmd
      - href: awards.qmd
      - href: applied_projects.qmd
      - href: interviews.qmd
      - href: blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full