project:
  type: website
  output-dir: docs

website:
  title: "Davi Moreira"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - books.qmd
      - awards.qmd
      - applied_projects.qmd
      - interviews.qmd
      - blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full