---
title: "Teaching"
---

My teaching expertise spans from math, statistics, programming languages, data science, machine learning, research design, and causal inference to political science courses tailored for both undergraduate and graduate students. Below you find the list of courses I taught - click the link and check the course material:

| Year.Semester.Quarter | Course title | Level   | Hours | Institution | Material |
|------------------------------------|------------------------------------------------------------|---------------|-------|-----------------|-----------------|
| 2024.Summer     | Data Science Computing                                     | Undergraduate | 60h   | Emory University| website |
| 2024.Summer     | Introduction to Statistical Inference                      | Undergraduate | 60h   | Emory University| syllabus |
| 2024.1          | Data Science Computing                                     | Undergraduate | 60h   | Emory University| [website](https://davi-moreira.github.io/2024S_dsc_emory_qtm_350){target="_blank"} |
| 2024.1          | Probability and Statistics                                 | Undergraduate | 60h   | Emory University| [syllabus](https://www.dropbox.com/scl/fi/trld01jbpu0x0ou15dgat/24S_QTM210_syllabus_short_20240214.pdf?rlkey=xumo8jh8k4mqy14edq7tfoiu8&dl=0){target="_blank"} |
| 2023.2          | Introduction to Statistical Inference                      | Undergraduate | 60h   | Emory University| [syllabus](https://www.dropbox.com/scl/fi/la21fyh6rkas3lxa4tc4q/23F_QTM100_05_syllabus.pdf?rlkey=kd72nf8dtupr0wud4il661od6&dl=0){target="_blank"} |
| 2023.Summer                     | Text as Data                                               | Graduate      | 15h   | UFMG            |  [syllabus](https://www.dropbox.com/scl/fi/defdzpeuji67l41pbucqy/txt4ps_mq_ufmg_2023.pdf?rlkey=6117sobp4l8r688tb6pn2nxl3&dl=0){target="_blank"} |
| 2023.1.Spring   | Text as Data                                               | Undergraduate | 30h   | UCSD            |  [syllabus](https://www.dropbox.com/scl/fi/0o8hhrwphcqx3yveql1mx/Poli176_DSC161_Syllabus_20230527.pdf?rlkey=65hp5gosqeub1m56ihrpslrqs&dl=0){target="_blank"}, [podcast videos](https://podcast.ucsd.edu/watch/sp23/poli176_a00/1){target="_blank"} |
| 2023.1.Spring                     | Democratic Backsliding in Latin America                    | Master        | 30h   | UCSD            | [syllabus](https://www.dropbox.com/scl/fi/iebj60ajltq5athpgxlr8/DBLA2023_logo_20230402.pdf?rlkey=cje7eelaussjsluiiffq8cwph&dl=0){target="_blank"} |
| 2023.1.Winter                     | Economic Policy in Latin America                           | Master        | 30h   | UCSD            | [syllabus](https://www.dropbox.com/scl/fi/1afg74ih0a8ueg94qjpfc/EPLA2023.pdf?rlkey=7z93ha0ybsr5c8631p9av3ssg&dl=0){target="_blank"} |
| 2022.2                             | TXT4PS - Text as Data for Political Science                | Graduate      | 60h   | UFPE            | [syllabus](https://www.dropbox.com/scl/fi/3v543fuotn4khnfvmb5id/78_txt4ps_syllabus_grad_ufpe_en.pdf?rlkey=26hv3vnh7bvr2bl3ppg4rvr3f&dl=0){target="_blank"} |
| 2022.1                             | PY4PS - Introduction to programming with Python for Political Science | Undergraduate | 60h   | UFPE            | [syllabus](https://www.dropbox.com/scl/fi/0r454h7emf3yf1qztao5m/py4ps_syllabus_undergrad_ufpe_20220630.pdf?rlkey=blbsq9u6i2ptna8kefjvqspin&dl=0){target="_blank"} |
| 2022.1                             | DS4PS - Data Science for Political Science                 | Graduate      | 60h   | UFPE            | [syllabus](https://www.dropbox.com/scl/fi/5tuxwbwfd4ryhiqstfoay/80_ds4ps_syllabus_grad_ufpe_20220531_pt_en.pdf?rlkey=j5358n3egm0lox802tejo5sew&dl=0){target="_blank"}|
| 2022.1                             | CI4PS - Causal Inference for Political Science - UFPE      | Undergraduate | 90h   | UFPE            | [syllabus](https://www.dropbox.com/scl/fi/0z94d7srgyy82urq68v11/81_20220904_ci4ps_syllabus_undergrad_pt_en.pdf?rlkey=slknqjhy7rup2c8l7ihw1nkb9&dl=0){target="_blank"}|
| 2021.2                             | DS4PS - Data Science for Political Science                 | Undergraduate | 90h   | UFPE            | [syllabus](https://www.dropbox.com/scl/fi/ov21nb9cswo15pnyye4sx/82_ds4ps_syllabus_undergrad_ufpe_20220326_pt_en.pdf?rlkey=23txytarp772vud5jts2lqzma&dl=0){target="_blank"}|
| 2021.2                             | Causal Inference                                           | Graduate      | 60h   | UFPE            | [syllabus](https://www.dropbox.com/scl/fi/e0dbsy69yu1npdijxdnhr/85_20211110_syllabus_causal_inference_pt_en.pdf?rlkey=u568udpi3saab5ea3py6vazgc&dl=0){target="_blank"}|
| 2021.2                             | Research Design 02                                         | Undergraduate | 120h  | UFPE            | [syllabus](https://www.dropbox.com/scl/fi/s55n1vropkk0nh1nl9v1j/83_ds4ps_syllabus_ufpe_20211006_pt_en.pdf?rlkey=lpfgfy8pksjco37ebxfzeai1y&dl=0){target="_blank"}|
| 2021.1                             | DS4PS - Data Science for Political Science                 | Undergraduate | 90h   | UFPE            | [syllabus](https://www.dropbox.com/scl/fi/s55n1vropkk0nh1nl9v1j/83_ds4ps_syllabus_ufpe_20211006_pt_en.pdf?rlkey=lpfgfy8pksjco37ebxfzeai1y&dl=0){target="_blank"}|
| 2021.1                             | DS4LAW-03 - Data Science for Law 03: text as data          | Graduate      | 30h   | FGV             | [syllabus](https://www.dropbox.com/scl/fi/l1fqndcolsnll404fkfr2/89_ds4law-03-fgv-20210607.pt.en.pdf?rlkey=6tqv3whlqk9zke5q480yusi6o&dl=0){target="_blank"}|
| 2021.1                             | DS4LAW-02 - Data Science for Law 02: data analysis and visualization advanced principles | Graduate | 30h   | FGV |  [syllabus](https://www.dropbox.com/scl/fi/nw3seintn3g3iq2hdgwqx/88_ds4law-02-fgv-20210516.pt.en.pdf?rlkey=3v6x1nltyhpz979pm76a102o4&dl=0){target="_blank"}|
| 2021.1                             | DS4LAW-01 - Data Science for Law 01: data analysis and visualization basic principles | Graduate | 30h   | FGV  |  [syllabus](https://www.dropbox.com/scl/fi/tqdgruhlprzg6jz1k7idr/87_ds4law-01-fgv-20210423.pt.en.pdf?rlkey=1bksgowiyqx4v52103burfjxr&dl=0){target="_blank"}|
| 2020.2                             | Data Science: math foundations                             | Undergraduate | 90h   | FGV             | [syllabus](https://www.dropbox.com/scl/fi/ib41hk7p62hkcgm7dx3qu/ds-math4ir-fgv-20201002.pdf?rlkey=rhrb9e4xgre3wmgqweiphfby1&dl=0){target="_blank"}|
| 2020.2                             | Data Science Project Management and Development            | Undergraduate | 60h   | FGV             | [syllabus](https://www.dropbox.com/scl/fi/tii65ws7hhjmh2ck3bd6k/ds-pm-syllabus-20201019.pdf?rlkey=r6j7osi51bn4nc1kynsdeato0&dl=0){target="_blank"}|
| 2020.2                             | DS4IR - Data Science for International Relations: data analysis and visualization | Undergraduate | 60h   | FGV |  [syllabus](https://www.dropbox.com/scl/fi/5in1pem1ra4ukk4d355x2/92_ds4ri-fgv-2020-winter-052020.pt.en.pdf?rlkey=7elz2fzs4xaddoq5izt6nq79f&dl=0){target="_blank"}           |
| 2019.2                             | Causal Inference                                           | Graduate      | 60h   | UFPE            | [syllabus](https://www.dropbox.com/scl/fi/4z7huwnul0ra8xbbsgqbi/93_20191104_programa_causal_inference_UFPE.pt.en.pdf?rlkey=dag3gih3vj5d8w96sik2h05u1&dl=0){target="_blank"}|
| 2023.Summer                             | TXT4SC - Text as Data for Social Sciences                  | Graduate      | 30h   | UFMG | [syllabus](https://www.dropbox.com/scl/fi/iofn9m7wbn8g04es2x2ry/94_programa_txt_data_mq_ufmg_2019.pt.en.pdf?rlkey=k57r648qzz6vq3nrpunab1xcd&dl=0){target="_blank"}|
| 2019.2                             | Research Design 02                                         | Undergraduate | 120h  | UFPE |  [syllabus](https://www.dropbox.com/scl/fi/w5296kxh2c1x16tjt3lgz/95_20190723_programa_TCC_UFPE.pdf?rlkey=2tygnprcapp4bq0dz2ypstk74&dl=0){target="_blank"}|
| 2019.1                             | Research Design 01                                         | Undergraduate | 60h   | UFPE | [syllabus](https://www.dropbox.com/scl/fi/p1v6qi14jzow5xaelwfft/96_20190215_programa_seminario_pesquisa_UFPE.pdf?rlkey=g9jwa6e5dmrpbig4fitemwyjw&dl=0){target="_blank"} |
| 2019.1                             | Data Analysis                                              | Graduate      | 60h   | UFPE | [syllabus](https://www.dropbox.com/scl/fi/36a5xzpil2fxixzd741uk/97_20190611_programa_analise_dados_UFPE.pdf?rlkey=f81y59hjlio0ru0cg19sd1geo&dl=0){target="_blank"}|
| 2018.2                             | Data Analysis                                              | Graduate      | 60h   | UFPE | [syllabus](https://www.dropbox.com/scl/fi/02f50qkgd4esduk3ofvnd/98_20181127_programa_analise_dados_UFPE_clean.pdf?rlkey=g6bp5jfxn206ge8nx95ilzy9t&dl=0){target="_blank"}|
| 2018.2                             | Introduction to R programming language                     | Graduate      | 20h   | UFPE | [syllabus](https://www.dropbox.com/scl/fi/a0xncpc66aim6wxtu4oxs/99_programa_intro_r_2018.pdf?rlkey=j21u0ld40zwsazejkivoo2fll&dl=0){target="_blank"}|

## 
